#!/bin/bash
# This script updates installed Alaterm.
# Ordinary usage, from within launched Alaterm:
# Enter this folder, then command:  bash update-alaterm

echo "Developer found a bug in this update script."
echo "Be patient. Installer script is OK."

