# Alaterm:file=$alatermTop/home/.bash_profile
# File /home/.bash_profile, created by Alaterm installer.

# Do not edit this file.
# It may be over-written when Alaterm is updated.

# Use ~/.bashrc for custom code, instead.

# Alaterm uses BASH shell only.
# Version 2 does not use /etc/bash.bashrc.
# This file is read immediately after /etc/profile, at user login.
# It gets variables stored in /status, sets some more environment,
# and cleans out a variety of files left-over from previous run.
# It runs some utility scripts to ensure the Menu is correct.
# Then it launches the GUI.
# Finally, it sources ~/.bashrc.

# Normally, you will never need to use su to change to root.
# But if you do, this file is not re-read when you exit root,
# so the GUI is not double-launched.

source /status # Get stored variables.
export EDITOR=/usr/bin/nano # User may over-ride.
export VISUAL=/usr/bin/nano # As above.
export BROWSER=/usr/bin/netsurf # User may over-ride, but unlikely.
export TMPDIR=/tmp # In Alaterm, not Android.
export ANDROID_DATA=/data # Same in Android, Termux, and Alaterm.
export ANDROID_ROOT=/system # Same in Android, Termux, and Alaterm.
export EXTERNAL_STORAGE=/sdcard # Actually built-in storage, not removable.
# Clear left-over tmp from previous launch:
rm -r -f /tmp/.* 2>/dev/null
rm -r -f /tmp/* 2>/dev/null
# Corrects for overly-enthusiastic user removal of unused locales:
touch /usr/share/locale/locale.alias
# Make annoying and useless desktop message go away:
rm -f /etc/xdg/autostart/lxpolkit.desktop
[ -f /usr/bin/lxpolkit ] && mv -f /usr/bin/lxpolkit /usr/bin/lxpolit.bak
# For use with dbus-run-session:
mkdir -p /tmp/runtime-user
export XDG_RUNTIME_DIR=/tmp/runtime-user
# Prevent ~/.cache and .bash_history from growing ever-larger:
rm -r -f ~/.cache
mkdir -p ~/.cache
c=/home/.cache/1-README
echo "This ~/.cache directory is emptied at each login." > "$c"
echo "Do not put anything here, if you need it later." >> "$c"
echo "Anything in ~/.cache was created at current login" >> "$c"
echo "and may increase during your current session." >> "$c"
rm -f ~/.lectured-root # Also remove this marker file, if present.
rm -f ~/.bash_history
# Ensure that the authority files, if present, are only for current session:
rm -f ~/.Xauthority && touch ~/.Xauthority
rm -f ~/.X11authority && touch ~/.X11authority
rm -f ~/.ICEauthority && touch ~/.ICEauthority
# Ensure no left-over .vnc files:
rm -f ~/.vnc/localhost*
# Prevent non-working programs from showing in LXDE Menu:
ban-menu-items 2>/dev/null # In /usr/local/scripts
# Ensure that certain basic programs are always default for their mimetypes:
edit-mimeinfo-cache 2>/dev/null # In /usr/local/scripts
sleep .1
# Required aliases:
alias ls='/usr/bin/ls --color=auto' # pretty-prints directory lists.
alias pacman='sudo pacman'
alias fc-cache='sudo fc-cache'
alias tlmgr='sudo tlmgr' # If user installs texlive.
# Launch GUI:
export DISPLAY=:1
printf "\e[1;92mStarting Alaterm. \e[0m"
vncserver # /usr/local/scripts/vncserver, not /usr/bin/vncserver.
echo -e "\e[92mView LXDE Desktop in VNC Viewer app. Password: password"
echo -e "To leave Alaterm and return to Termux: logout\e[0m\n";
sleep .1
#
[ -f /home/.bashrc ] && source /home/.bashrc # For both login and non-login.
##
