# Alaterm:file=$alatermTop/etc/profile
# File /etc/profile edited by Alaterm installer.

# Do not edit this file.
# It may be over-written when Alaterm is updated.

umask 022 # Termux settings may over-ride this.
# Priority to /usr/local/scripts and /usr/local/bin:
PATH="/usr/local/scripts:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export PATH
# Load profiles from /etc/profile.d.
# Among other things, this may add perl to PATH:
if [ -d /etc/profile.d/ ] ; then
	for profile in /etc/profile.d/*.sh ; do
		[ -r "$profile" ] && source "$profile"
	done
	unset profile
fi
unset TERMCAP
unset MANPATH
# Alaterm version 2 does not use /etc/bash.bashrc.
# File /home/.bash_profile is read next.
##
